# Generated by Django 5.0.7 on 2024-07-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_item_address_remove_item_birthday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='permanent_subd',
            new_name='college',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name_ext',
        ),
        migrations.AddField(
            model_name='item',
            name='elementary_school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='junior_high_school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='senior_high_school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
